#!/bin/bash

REPO=Blog
BRAN=master
WDIR="/home/ec2-user"

cd $WDIR
if [ ! -d $REPO ]; then
	mkdir $REPO
	git clone https://github.com/4Oranges/$REPO -b $BRAN
fi

cd $REPO

sudo git pull

rm -rf /var/www/html/*
cp -r * /var/www/html/

echo "fix permission..."
$WDIR/fix_www_permission
echo "done"
