#!/bin/env bash

TARGET_DIR="/var/www"

sudo chown -R root:root $TARGET_DIR
sudo chmod 2775 $TARGET_DIR
find $TARGET_DIR -type d -exec sudo chmod 2775 {} \;
find $TARGET_DIR -type f -exec sudo chmod 0664 {} \;

