#!/bin/bash

INSTALL_LIST=(blog-deploy blog-fixpermission)
INSTALL_PATH_TOOLS="/usr/local/bin"
STAGE_DELIMITER="====================================="

REPO=Blog
BRAN=master
REPO_DIR="/root"
DEPLOY_DIR="/var/www/html"

cd $REPO_DIR
if [ ! -d $REPO ]; then
	mkdir $REPO
	git clone https://github.com/4Oranges/$REPO -b $BRAN
	cd $REPO
	git submodule init
	git submodule update
fi

cd $REPO

git pull

cd ZFrame
git fetch
git merge origin/master
cd ..

cd deploy
echo $STAGE_DELIMITER
echo "update blog maintenance tools..."
for file in ${INSTALL_LIST[*]}; do
    echo "installing $file to $INSTALL_PATH_TOOLS ..." && sudo install -m 755 -o root $file $INSTALL_PATH_TOOLS/$file && echo "success" || `echo "installation failed, exiting..." && exit`
done
echo
cd ..

rm -rf $DEPLOY_DIR/*
cp -r * $DEPLOY_DIR/
rm -rf $DEPLOY_DIR/deploy

#rsync -r --exclude=server_settings * $DEPLOY_DIR/

echo "fix permission..."
blog-fixpermission
echo "done"
