#!/bin/env bash

INSTALL_LIST=(blog-deploy blog-fixpermission)
INSTALL_PATH_TOOLS="/usr/local/bin"
STAGE_DELIMITER="====================================="
alias next_stage_delimiter="printf \"${STAGE_DELIMITER}\n\""

REPO=Blog
BRAN=master
REPO_DIR="/root"
DEPLOY_DIR="/var/www/html"

cd $REPO_DIR
if [ ! -d $REPO ]; then
	mkdir $REPO
	git clone https://github.com/4Oranges/$REPO -b $BRAN
	cd $REPO
	git submodule init
	git submodule update
        next_stage_delimiter
fi

cd $REPO
git pull
cd ZFrame
git fetch
git merge origin/master
cd ..
next_stage_delimiter

cd deploy
echo "update blog maintenance tools..."
for file in ${INSTALL_LIST[*]}; do
    echo "installing $file to $INSTALL_PATH_TOOLS ..." && install -m 755 -o root $file $INSTALL_PATH_TOOLS/$file && echo "success" || `echo "installation failed, exiting..." && exit`
done
cd ..
next_stage_delimiter

rm -rf $DEPLOY_DIR/*
cp -r * $DEPLOY_DIR/
rm -rf $DEPLOY_DIR/deploy
next_stage_delimiter

#rsync -r --exclude=server_settings * $DEPLOY_DIR/

echo "fix permission..."
blog-fixpermission
echo "done"
